export const INIT_TASK_LIST = 'INIT_TASK_LIST'
export const INIT_TOTAL_OBJ = 'INIT_TOTAL_OBJ'
export const SAVE_TASK = 'SAVE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const FINISH_TASK = 'FINISH_TASK'
export const ADD_TOTAL = 'ADD_TOTAL'
export const SUBTRACT_TOTAL = 'SUBTRACT_TOTAL'
